services:
  php-apache:
    image: php:8.2-apache
    container_name: php-apache
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
    networks:
      - php_network
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=users
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_pass
    command: >
      /bin/bash -c "
        apt-get update &&
        apt-get install -y default-mysql-client &&
        docker-php-ext-install mysqli &&
        docker-php-ext-enable mysqli &&
        a2enmod rewrite &&
        chown -R www-data:www-data /var/www/html &&
        chmod -R 755 /var/www/html &&
        apache2-foreground
      "

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - php_network

networks:
  php_network:
    driver: bridge

volumes:
  mysql_data:
