version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"  
    volumes:
      - .:/var/www/html
    networks:
      - php_network
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=users
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_pass

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - php_network

networks:
  php_network:
    driver: bridge

volumes:
  mysql_data:


# version : '3.8'

# services: 
#   mysql:
#     container_name: mysql
#     image: mysql:5.7
#     volume: 
#       - mysql_volume:/var/lib/mysql
#     ports:
#       - 3307:3306
#     networks:
#       - mysql_network

  # php: 
  #   build: .
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - .:/var/www/html
    
  #   depends_on:
  #     -mysql

  #   networks:
  #     - mysql_network

  #   nginx:
  #     networks:
  #       - mysql_network


